# Generated by Django 5.1.6 on 2025-03-21 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("InternationalChallenges", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sensordata",
            name="RSSI",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sensordata",
            name="SNR",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sensordata",
            name="pressure",
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
